Sign up/sign in
CraftAcademy/homechef-mobile pull request #5
Opened 2017-02-09 15:58 UTC by aniansson

## Pivotal Tracker story

https://www.pivotaltracker.com/story/show/139265229

## Changes proposed in this pull request:

This feature makes it possible for new users to sign up + existing users to sign in

## What I have learned working on this feature:

How everything links together in the client  (modals, views, controllers, scope etc.) and how to create not only a sign in option but sign up in a similar way. And how it links to the API.

### Ready for review!

2017-02-09 16:44 UTC, tochman requested changes

2017-02-09 16:44 UTC, tochman commented on www/js/controllers.js
> +      $scope.loginmodal = modal;
I would use pascalCase here: `loginModal`. Same thing below.

2017-02-09 16:44 UTC, tochman commented on www/js/controllers.js
> +          $scope.showAlert('Failure', response.data.errors.full_messages);
`errors.full_messages` is an Array. I would like to see a screenshot of what this looks like if there are more than one error

2017-02-09 16:44 UTC, tochman commented on www/js/controllers.js
> +    });
What does this do for you?

2017-02-09 16:44 UTC, tochman commented on www/js/controllers.js
> +  })
Same question here, why are you including this?

2017-02-09 16:44 UTC, tochman commented on www/js/controllers.js
> +      dishes.query(function (response) {
Is `dishes` a name of a service? I would revisit this naming. I usually use singular format and capital. `Dish` Like a class name in ruby. But there are many standards. `dishService` is one option.

2017-02-09 16:44 UTC, tochman commented on www/js/controllers.js
> +      });
If you dont intend to handle errors, plz remove this callback.

2017-02-09 18:30 UTC, Philippoes commented on www/js/controllers.js
> +      $scope.loginmodal = modal;
Got it.

2017-02-09 18:37 UTC, Philippoes commented on www/js/controllers.js
> +          $scope.showAlert('Failure', response.data.errors.full_messages);
<img width="315" alt="screen shot 2017-02-09 at 19 36 06" src="https://cloud.githubusercontent.com/assets/22058587/22797609/2c19f8e0-eeff-11e6-9d6a-e9d3e4ddfa05.png">

2017-02-09 18:43 UTC, Philippoes commented on www/js/controllers.js
> +    });
I assumed this was an AUTH event. Like when the login is successful, currentUser becomes the user which has just logged in. It is basically a way for the app to know which user is currently using it. And i think that when there's a new request (for example add to order where user has to be logged in), the app will send that header with the request, so the api knows which user's order to handle. Am I right? @tochman

2017-02-09 19:12 UTC, tochman commented on www/js/controllers.js
> +          $scope.showAlert('Failure', response.data.errors.full_messages);
The formatting feels a bit off. Are you guys happy with this?

2017-02-09 19:14 UTC, tochman commented on www/js/controllers.js
> +    });
With ngTokenAuth you automatically have 
$scope.user available. No need for any further setup. Try without this.

2017-02-09 19:17 UTC, diraulo requested changes
see comment about api url

2017-02-09 19:17 UTC, diraulo commented on www/js/app.js
> +  .constant('API_URL', 'http://localhost:3000/api/v1')
shouldn't this URL be the one deployed on heroku?

2017-02-09 19:17 UTC, aniansson commented on www/js/app.js
> +  .constant('API_URL', 'http://localhost:3000/api/v1')
We had problems with the deployed one therefore we put int he localhost one

2017-02-10 08:42 UTC, Philippoes commented on www/js/controllers.js
> +    });
I tried without this. Now I cannot access the current user for its email or checking if it's there. I have googled on how to use the ng token auth default user helper but with no luck.

2017-02-10 09:08 UTC, Philippoes commented on www/js/app.js
> +  .constant('API_URL', 'http://localhost:3000/api/v1')
It is changed to the heroku app. now. We used it mainly for testing purposes.

2017-02-10 09:34 UTC, tochman approved these changes

2017-02-10 09:34 UTC, tochman commented on www/js/controllers.js
> +    });
You can probably access `$scope.user` without it.

2017-02-10 09:44 UTC, Philippoes commented on www/js/controllers.js
> +    });
Okay well. I tried setting it: `<ion-item menu-close ng-if="!user" ng-click="login()">` (see ng-if) and the menu item still shows up even though i logged in. I tried console logging user.email but with no result.  @tochman

2017-02-10 09:47 UTC, diraulo approved these changes

2017-02-10 09:47 UTC, merged